CREATE TABLE proyectobd.eventos (
  id int( 11 ) NOT NULL AUTO_INCREMENT,
  nombre varchar( 50 ) DEFAULT NULL,
  fecha int(1 1 ) DEFAULT NULL,
  PRIMARY KEY ( id )
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8